// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vsrtferrum/AvitoIntro/models"
)

// GetAPIInfoOKCode is the HTTP code returned for type GetAPIInfoOK
const GetAPIInfoOKCode int = 200

/*
GetAPIInfoOK Успешный ответ.

swagger:response getApiInfoOK
*/
type GetAPIInfoOK struct {

	/*
	  In: Body
	*/
	Payload *models.InfoResponse `json:"body,omitempty"`
}

// NewGetAPIInfoOK creates GetAPIInfoOK with default headers values
func NewGetAPIInfoOK() *GetAPIInfoOK {

	return &GetAPIInfoOK{}
}

// WithPayload adds the payload to the get Api info o k response
func (o *GetAPIInfoOK) WithPayload(payload *models.InfoResponse) *GetAPIInfoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Api info o k response
func (o *GetAPIInfoOK) SetPayload(payload *models.InfoResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPIInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAPIInfoBadRequestCode is the HTTP code returned for type GetAPIInfoBadRequest
const GetAPIInfoBadRequestCode int = 400

/*
GetAPIInfoBadRequest Неверный запрос.

swagger:response getApiInfoBadRequest
*/
type GetAPIInfoBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetAPIInfoBadRequest creates GetAPIInfoBadRequest with default headers values
func NewGetAPIInfoBadRequest() *GetAPIInfoBadRequest {

	return &GetAPIInfoBadRequest{}
}

// WithPayload adds the payload to the get Api info bad request response
func (o *GetAPIInfoBadRequest) WithPayload(payload *models.ErrorResponse) *GetAPIInfoBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Api info bad request response
func (o *GetAPIInfoBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPIInfoBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAPIInfoUnauthorizedCode is the HTTP code returned for type GetAPIInfoUnauthorized
const GetAPIInfoUnauthorizedCode int = 401

/*
GetAPIInfoUnauthorized Неавторизован.

swagger:response getApiInfoUnauthorized
*/
type GetAPIInfoUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetAPIInfoUnauthorized creates GetAPIInfoUnauthorized with default headers values
func NewGetAPIInfoUnauthorized() *GetAPIInfoUnauthorized {

	return &GetAPIInfoUnauthorized{}
}

// WithPayload adds the payload to the get Api info unauthorized response
func (o *GetAPIInfoUnauthorized) WithPayload(payload *models.ErrorResponse) *GetAPIInfoUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Api info unauthorized response
func (o *GetAPIInfoUnauthorized) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPIInfoUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAPIInfoInternalServerErrorCode is the HTTP code returned for type GetAPIInfoInternalServerError
const GetAPIInfoInternalServerErrorCode int = 500

/*
GetAPIInfoInternalServerError Внутренняя ошибка сервера.

swagger:response getApiInfoInternalServerError
*/
type GetAPIInfoInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetAPIInfoInternalServerError creates GetAPIInfoInternalServerError with default headers values
func NewGetAPIInfoInternalServerError() *GetAPIInfoInternalServerError {

	return &GetAPIInfoInternalServerError{}
}

// WithPayload adds the payload to the get Api info internal server error response
func (o *GetAPIInfoInternalServerError) WithPayload(payload *models.ErrorResponse) *GetAPIInfoInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Api info internal server error response
func (o *GetAPIInfoInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPIInfoInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
