// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vsrtferrum/AvitoIntro/models"
)

// GetAPIBuyItemOKCode is the HTTP code returned for type GetAPIBuyItemOK
const GetAPIBuyItemOKCode int = 200

/*
GetAPIBuyItemOK Успешный ответ.

swagger:response getApiBuyItemOK
*/
type GetAPIBuyItemOK struct {
}

// NewGetAPIBuyItemOK creates GetAPIBuyItemOK with default headers values
func NewGetAPIBuyItemOK() *GetAPIBuyItemOK {

	return &GetAPIBuyItemOK{}
}

// WriteResponse to the client
func (o *GetAPIBuyItemOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetAPIBuyItemBadRequestCode is the HTTP code returned for type GetAPIBuyItemBadRequest
const GetAPIBuyItemBadRequestCode int = 400

/*
GetAPIBuyItemBadRequest Неверный запрос.

swagger:response getApiBuyItemBadRequest
*/
type GetAPIBuyItemBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetAPIBuyItemBadRequest creates GetAPIBuyItemBadRequest with default headers values
func NewGetAPIBuyItemBadRequest() *GetAPIBuyItemBadRequest {

	return &GetAPIBuyItemBadRequest{}
}

// WithPayload adds the payload to the get Api buy item bad request response
func (o *GetAPIBuyItemBadRequest) WithPayload(payload *models.ErrorResponse) *GetAPIBuyItemBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Api buy item bad request response
func (o *GetAPIBuyItemBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPIBuyItemBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAPIBuyItemUnauthorizedCode is the HTTP code returned for type GetAPIBuyItemUnauthorized
const GetAPIBuyItemUnauthorizedCode int = 401

/*
GetAPIBuyItemUnauthorized Неавторизован.

swagger:response getApiBuyItemUnauthorized
*/
type GetAPIBuyItemUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetAPIBuyItemUnauthorized creates GetAPIBuyItemUnauthorized with default headers values
func NewGetAPIBuyItemUnauthorized() *GetAPIBuyItemUnauthorized {

	return &GetAPIBuyItemUnauthorized{}
}

// WithPayload adds the payload to the get Api buy item unauthorized response
func (o *GetAPIBuyItemUnauthorized) WithPayload(payload *models.ErrorResponse) *GetAPIBuyItemUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Api buy item unauthorized response
func (o *GetAPIBuyItemUnauthorized) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPIBuyItemUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAPIBuyItemInternalServerErrorCode is the HTTP code returned for type GetAPIBuyItemInternalServerError
const GetAPIBuyItemInternalServerErrorCode int = 500

/*
GetAPIBuyItemInternalServerError Внутренняя ошибка сервера.

swagger:response getApiBuyItemInternalServerError
*/
type GetAPIBuyItemInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetAPIBuyItemInternalServerError creates GetAPIBuyItemInternalServerError with default headers values
func NewGetAPIBuyItemInternalServerError() *GetAPIBuyItemInternalServerError {

	return &GetAPIBuyItemInternalServerError{}
}

// WithPayload adds the payload to the get Api buy item internal server error response
func (o *GetAPIBuyItemInternalServerError) WithPayload(payload *models.ErrorResponse) *GetAPIBuyItemInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Api buy item internal server error response
func (o *GetAPIBuyItemInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPIBuyItemInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
