// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAPIInfoHandlerFunc turns a function with the right signature into a get API info handler
type GetAPIInfoHandlerFunc func(GetAPIInfoParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAPIInfoHandlerFunc) Handle(params GetAPIInfoParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetAPIInfoHandler interface for that can handle valid get API info params
type GetAPIInfoHandler interface {
	Handle(GetAPIInfoParams, interface{}) middleware.Responder
}

// NewGetAPIInfo creates a new http.Handler for the get API info operation
func NewGetAPIInfo(ctx *middleware.Context, handler GetAPIInfoHandler) *GetAPIInfo {
	return &GetAPIInfo{Context: ctx, Handler: handler}
}

/*
	GetAPIInfo swagger:route GET /api/info getApiInfo

Получить информацию о монетах, инвентаре и истории транзакций.
*/
type GetAPIInfo struct {
	Context *middleware.Context
	Handler GetAPIInfoHandler
}

func (o *GetAPIInfo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAPIInfoParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
