// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAPIBuyItemHandlerFunc turns a function with the right signature into a get API buy item handler
type GetAPIBuyItemHandlerFunc func(GetAPIBuyItemParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAPIBuyItemHandlerFunc) Handle(params GetAPIBuyItemParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetAPIBuyItemHandler interface for that can handle valid get API buy item params
type GetAPIBuyItemHandler interface {
	Handle(GetAPIBuyItemParams, interface{}) middleware.Responder
}

// NewGetAPIBuyItem creates a new http.Handler for the get API buy item operation
func NewGetAPIBuyItem(ctx *middleware.Context, handler GetAPIBuyItemHandler) *GetAPIBuyItem {
	return &GetAPIBuyItem{Context: ctx, Handler: handler}
}

/*
	GetAPIBuyItem swagger:route GET /api/buy/{item} getApiBuyItem

Купить предмет за монеты.
*/
type GetAPIBuyItem struct {
	Context *middleware.Context
	Handler GetAPIBuyItemHandler
}

func (o *GetAPIBuyItem) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAPIBuyItemParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
