// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vsrtferrum/AvitoIntro/models"
)

// PostAPIAuthOKCode is the HTTP code returned for type PostAPIAuthOK
const PostAPIAuthOKCode int = 200

/*
PostAPIAuthOK Успешная аутентификация.

swagger:response postApiAuthOK
*/
type PostAPIAuthOK struct {

	/*
	  In: Body
	*/
	Payload *models.AuthResponse `json:"body,omitempty"`
}

// NewPostAPIAuthOK creates PostAPIAuthOK with default headers values
func NewPostAPIAuthOK() *PostAPIAuthOK {

	return &PostAPIAuthOK{}
}

// WithPayload adds the payload to the post Api auth o k response
func (o *PostAPIAuthOK) WithPayload(payload *models.AuthResponse) *PostAPIAuthOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post Api auth o k response
func (o *PostAPIAuthOK) SetPayload(payload *models.AuthResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAPIAuthOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAPIAuthBadRequestCode is the HTTP code returned for type PostAPIAuthBadRequest
const PostAPIAuthBadRequestCode int = 400

/*
PostAPIAuthBadRequest Неверный запрос.

swagger:response postApiAuthBadRequest
*/
type PostAPIAuthBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPostAPIAuthBadRequest creates PostAPIAuthBadRequest with default headers values
func NewPostAPIAuthBadRequest() *PostAPIAuthBadRequest {

	return &PostAPIAuthBadRequest{}
}

// WithPayload adds the payload to the post Api auth bad request response
func (o *PostAPIAuthBadRequest) WithPayload(payload *models.ErrorResponse) *PostAPIAuthBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post Api auth bad request response
func (o *PostAPIAuthBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAPIAuthBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAPIAuthUnauthorizedCode is the HTTP code returned for type PostAPIAuthUnauthorized
const PostAPIAuthUnauthorizedCode int = 401

/*
PostAPIAuthUnauthorized Неавторизован.

swagger:response postApiAuthUnauthorized
*/
type PostAPIAuthUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPostAPIAuthUnauthorized creates PostAPIAuthUnauthorized with default headers values
func NewPostAPIAuthUnauthorized() *PostAPIAuthUnauthorized {

	return &PostAPIAuthUnauthorized{}
}

// WithPayload adds the payload to the post Api auth unauthorized response
func (o *PostAPIAuthUnauthorized) WithPayload(payload *models.ErrorResponse) *PostAPIAuthUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post Api auth unauthorized response
func (o *PostAPIAuthUnauthorized) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAPIAuthUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAPIAuthInternalServerErrorCode is the HTTP code returned for type PostAPIAuthInternalServerError
const PostAPIAuthInternalServerErrorCode int = 500

/*
PostAPIAuthInternalServerError Внутренняя ошибка сервера.

swagger:response postApiAuthInternalServerError
*/
type PostAPIAuthInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPostAPIAuthInternalServerError creates PostAPIAuthInternalServerError with default headers values
func NewPostAPIAuthInternalServerError() *PostAPIAuthInternalServerError {

	return &PostAPIAuthInternalServerError{}
}

// WithPayload adds the payload to the post Api auth internal server error response
func (o *PostAPIAuthInternalServerError) WithPayload(payload *models.ErrorResponse) *PostAPIAuthInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post Api auth internal server error response
func (o *PostAPIAuthInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAPIAuthInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
