// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SendCoinRequest send coin request
//
// swagger:model SendCoinRequest
type SendCoinRequest struct {

	// Количество монет, которые необходимо отправить.
	// Required: true
	Amount *int64 `json:"amount"`

	// Имя пользователя, которому нужно отправить монеты.
	// Required: true
	ToUser *string `json:"toUser"`
}

// Validate validates this send coin request
func (m *SendCoinRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateToUser(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SendCoinRequest) validateAmount(formats strfmt.Registry) error {

	if err := validate.Required("amount", "body", m.Amount); err != nil {
		return err
	}

	return nil
}

func (m *SendCoinRequest) validateToUser(formats strfmt.Registry) error {

	if err := validate.Required("toUser", "body", m.ToUser); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this send coin request based on context it is used
func (m *SendCoinRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SendCoinRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SendCoinRequest) UnmarshalBinary(b []byte) error {
	var res SendCoinRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
